# -*- coding: utf-8 -*-
"""Curated candidate papers (biased toward visually rich papers).
The matcher verifies venue/year authoritatively; unmatched items are dropped.
"""

CANDIDATES = [
    # ---------------- NeurIPS 2023 ----------------
    ("neurips", 2023, "Tree of Thoughts: Deliberate Problem Solving with Large Language Models", "conceptual"),
    ("neurips", 2023, "Reflexion: Language Agents with Verbal Reinforcement Learning", "framework"),
    ("neurips", 2023, "Self-Refine: Iterative Refinement with Self-Feedback", "framework"),
    ("neurips", 2023, "Toolformer: Language Models Can Teach Themselves to Use Tools", "pipeline"),
    ("neurips", 2023, "Direct Preference Optimization: Your Language Model is Secretly a Reward Model", "conceptual"),
    ("neurips", 2023, "QLoRA: Efficient Finetuning of Quantized Language Models", "architecture"),
    ("neurips", 2023, "Visual Instruction Tuning", "framework"),
    ("neurips", 2023, "InstructBLIP: Towards General-purpose Vision-Language Models with Instruction Tuning", "framework"),
    ("neurips", 2023, "Hyena Hierarchy: Towards Larger Convolutional Language Models", "architecture"),
    ("neurips", 2023, "Retentive Network: A Successor to Transformer for Large Language Models", "architecture"),
    ("neurips", 2023, "H2O: Heavy-Hitter Oracle for Efficient Generative Inference of Large Language Models", "conceptual"),
    ("neurips", 2023, "Mind2Web: Towards a Generalist Agent for the Web", "framework"),
    ("neurips", 2023, "HuggingGPT: Solving AI Tasks with ChatGPT and its Friends", "framework"),
    ("neurips", 2023, "LIMA: Less Is More for Alignment", "pipeline"),
    ("neurips", 2023, "Consistency Models", "conceptual"),
    ("neurips", 2023, "DPM-Solver-v3: Improved Diffusion ODE Solver with Empirical Model Order Reduction", "results"),
    ("neurips", 2023, "mPLUG-Owl2: Revolutionizing Multi-modal Large Language Model with Modality Collaboration", "architecture"),
    ("neurips", 2023, "Unlimiformer: Long-Range Transformers with Unlimited Length Input", "architecture"),
    ("neurips", 2023, "DoReMi: Optimizing Data Mixtures Speeds Up Language Model Pretraining", "pipeline"),
    ("neurips", 2023, "ZipLoRA: Any Subject in Any Style by Effectively Merging LoRAs", "teaser"),
    ("neurips", 2023, "DataComp: In search of the next generation of multimodal datasets", "taxonomy"),
    ("neurips", 2023, "Matryoshka Representation Learning", "conceptual"),
    ("neurips", 2023, "ExpeL: LLM Agent with Experiential Learning", "framework"),
    ("neurips", 2023, "SwiftSage: A Generative Agent with Fast and Slow Thinking for Complex Interactive Tasks", "framework"),
    ("neurips", 2023, "Language Agent Tree Search Unifies Reasoning, Acting, and Planning in Language Models", "framework"),
    ("neurips", 2023, "LEACE: Perfect linear concept erasure in closed form", "conceptual"),
    ("neurips", 2023, "Scaling Data-Constrained Language Models", "results"),
    ("neurips", 2023, "Gorilla: Large Language Model Connected with Massive APIs", "framework"),
    ("neurips", 2023, "The Perception Test: A Diagnostic Benchmark for Multimodal Video Models", "taxonomy"),
    # ---------------- NeurIPS 2024 ----------------
    ("neurips", 2024, "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering", "framework"),
    ("neurips", 2024, "OSWorld: Benchmarking Multimodal Agents for Open-Ended Tasks in Real Computer Applications", "teaser"),
    ("neurips", 2024, "VisualWebArena: Evaluating Multimodal Agents on Visually Grounded Real-World Web Tasks", "teaser"),
    ("neurips", 2024, "LLaVA-OneVision: Easy Visual Task Transfer", "framework"),
    ("neurips", 2024, "LLaVA-Plus: Learning to Use Tools for Creating Multimodal Agents", "framework"),
    ("neurips", 2024, "Sparse Feature Circuits: Discovering and Editing Interpretable Causal Graphs in Language Models", "conceptual"),
    ("neurips", 2024, "MLE-bench: Evaluating Machine Learning Agents on Machine Learning Engineering", "taxonomy"),
    ("neurips", 2024, "HippoRAG: Neurobiologically Inspired Long-Term Memory for Large Language Models", "conceptual"),
    ("neurips", 2024, "LiveCodeBench: Hallucination-free and contamination-free evaluation of LLMs for code", "taxonomy"),
    ("neurips", 2024, "SimPO: Simple Preference Optimization with a Reference-Free Reward", "conceptual"),
    ("neurips", 2024, "EAGLE-2: Faster Inference of LLMs with Dynamic Drafting and Confidence-based Verifying", "pipeline"),
    ("neurips", 2024, "QuIP#: Even Better LLM Quantization with Hadamard Rotation and Incoherence Processing", "architecture"),
    ("neurips", 2024, "QuaRot: Outlier-Free 4-Bit Inference in Rotated Transformers", "conceptual"),
    ("neurips", 2024, "KVQuant: Towards 10 Million Context Length LLM Inference with KV Cache Quantization", "architecture"),
    ("neurips", 2024, "SGLang: Efficient Execution of Structured Language Model Programs", "architecture"),
    ("neurips", 2024, "LongVideoBench: A Benchmark for Long-context Interleaved Video-Language Understanding", "taxonomy"),
    ("neurips", 2024, "MileBench: Benchmarking MLLMs in Long Context", "taxonomy"),
    ("neurips", 2024, "MuJoCo Playground: An open-source framework for GPU-accelerated robot learning and sim-to-real transfer at scale", "framework"),
    ("neurips", 2024, "MambaOut: Do We Really Need Mamba for Vision?", "conceptual"),
    ("neurips", 2024, "VMamba: Visual State Space Model", "architecture"),
    ("neurips", 2024, "Improved Distribution Matching Distillation for Fast Image Synthesis", "pipeline"),
    ("neurips", 2024, "Phased Consistency Models", "conceptual"),
    ("neurips", 2024, "Diffusion for World Modeling: Visual Details Matter in Atari", "teaser"),
    ("neurips", 2024, "Large Gaussian Reconstruction Model for Efficient 3D Reconstruction and Generation", "pipeline"),
    ("neurips", 2024, "Lumina-mGPT: Illuminate Flexible Photorealistic Text-to-Image Generation with Multimodal Generative Pretraining", "framework"),
    ("neurips", 2024, "FineWeb-Edu: scaling high-quality educational data for the next generation of language models", "pipeline"),
    ("neurips", 2024, "OpenMathInstruct-2: Accelerating AI for Math with Massive Open-Source Instruction Data", "pipeline"),
    ("neurips", 2024, "RewardBench: Evaluating Reward Models for Language Modeling", "taxonomy"),
    ("neurips", 2024, "RoboVerse: towards a unified platform for scalable robot learning and simulation", "framework"),
    # ---------------- ICML 2023 ----------------
    ("icml", 2023, "BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models", "architecture"),
    ("icml", 2023, "Consistency Models", "conceptual"),
    ("icml", 2023, "VIMA: General Robot Manipulation with Multimodal Prompts", "teaser"),
    ("icml", 2023, "Learning Universal Policies via Text-Guided Video Generation", "conceptual"),
    ("icml", 2023, "SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models", "architecture"),
    ("icml", 2023, "SpQR: A Sparse-Quantized Representation for Near-Lossless LLM Weight Compression", "architecture"),
    ("icml", 2023, "Hungry Hungry Hippos: Towards Language Modeling with State Space Models", "architecture"),
    ("icml", 2023, "Simple Diffusion: End-to-end Diffusion for High Resolution", "conceptual"),
    ("icml", 2023, "A Watermark for Large Language Models", "conceptual"),
    ("icml", 2023, "REPLUG: Retrieval-Augmented Black-Box Language Models", "pipeline"),
    ("icml", 2023, "Scaling Vision Transformers to 22 Billion Parameters", "architecture"),
    ("icml", 2023, "Diffusion Models as Plug-and-Play Priors", "framework"),
    ("icml", 2023, "Visual Programming: Compositional visual reasoning without training", "pipeline"),
    ("icml", 2023, "Compositional Exemplars for In-context Learning", "conceptual"),
    # ---------------- ICML 2024 ----------------
    ("icml", 2024, "DoRA: Weight-Decomposed Low-Rank Adaptation", "conceptual"),
    ("icml", 2024, "GaLore: Memory-Efficient LLM Training by Gradient Low-Rank Projection", "conceptual"),
    ("icml", 2024, "Sophia: A Scalable Stochastic Second-order Optimizer for Language Model Pre-training", "architecture"),
    ("icml", 2024, "Zoology: Measuring and Improving Recall in Efficient Language Models", "results"),
    ("icml", 2024, "Simple Linear-Time Attention with Sparse Delta Denoising", "architecture"),
    ("icml", 2024, "Gated Linear Attention Transformers with Hardware-Efficient Training", "architecture"),
    ("icml", 2024, "Blockwise Parallel Transformer for Long Context Large Models", "architecture"),
    ("icml", 2024, "Quiet-STaR: Language Models Can Teach Themselves to Think Before Speaking", "conceptual"),
    ("icml", 2024, "3D-VLA: A 3D Vision-Language-Action Generative World Model", "architecture"),
    ("icml", 2024, "RoboDreamer: Learning Compositional World Models for Robot Imagination, Planning, and Control", "teaser"),
    ("icml", 2024, "Aligning Your Steps: Optimizing Noise and Model in Rectified Flows", "conceptual"),
    ("icml", 2024, "MM-Vet: Evaluating Large Multimodal Models for Integrated Capabilities", "taxonomy"),
    ("icml", 2024, "PLLaVA: Small Language Models Can Also Be Strong in Vision-Language Tasks", "architecture"),
    ("icml", 2024, "OpenFlamingo: An Open-Source Framework for Training of Vision-Language Models with In-Context Learning", "framework"),
    ("icml", 2024, "CodeAct: Executable Code Actions Elicit Better LLM Agents", "conceptual"),
    ("icml", 2024, "Mamba-2: How to Control Your State Space Model for Structured State Space Duality", "architecture"),
    ("icml", 2024, "Vision Mamba: Efficient Visual Representation Learning with Bidirectional State Space Model", "architecture"),
    ("icml", 2024, "Transformers as Support Vector Machines", "conceptual"),
    ("icml", 2024, "Boundless DAS: Finding Unbounded Distributed Representations in LLMs", "conceptual"),
    ("icml", 2024, "EAGLE: Speculative Sampling Requires Rethinking Feature Uncertainty", "pipeline"),
    ("icml", 2024, "Medusa: Simple LLM Inference Acceleration Framework with Multiple Decoding Heads", "architecture"),
    ("icml", 2024, "KIVI: A Tuning-Free Asymmetric 2bit Quantization for KV Cache", "architecture"),
    ("icml", 2024, "KTO: Model Alignment as Prospect Theoretic Optimization", "conceptual"),
    ("icml", 2024, "MobileLLM: Optimizing Sub-billion Parameter Language Models for On-Device Use Cases", "architecture"),
    ("icml", 2024, "Self-Rewarding Language Models", "pipeline"),
    ("icml", 2024, "Self-Play Fine-Tuning Converts Weak Language Models to Strong Language Models", "conceptual"),
    ("icml", 2024, "Diffusion Language Models Are Versatile Alternative Learners", "conceptual"),
    ("icml", 2024, "DataComp-LM: In search of the next generation of training sets for language models", "pipeline"),
    ("icml", 2024, "xLSTM: Extended Long Short-Term Memory", "architecture"),
    ("icml", 2024, "Resurrecting Recurrent Neural Networks for Long Sequences", "architecture"),
    ("icml", 2024, "Caduceus: Bi-Directional Equivariant Long-Range DNA Sequence Modeling", "architecture"),
    ("icml", 2024, "DNABERT-2: Efficient Foundation Model and Benchmark for Genomic Sequence", "architecture"),
    ("icml", 2024, "Score Identity Distillation for Data-free One-step Diffusion Sampling", "pipeline"),
    # ---------------- ICML 2025 (supplemented by keyword search) ----------------
    ("icml", 2025, "BigCodeBench: Benchmarking Code Generation with Diverse Function Calls and Complex Instructions", "taxonomy"),
    ("icml", 2025, "TinyVLA: Towards Efficient Vision-Language-Action Model with Visual Token Compression", "architecture"),
    # ---------------- ICLR 2023 ----------------
    ("iclr", 2023, "DreamFusion: Text-to-3D using 2D Diffusion", "teaser"),
    ("iclr", 2023, "Muse: Text-To-Image Generation via Masked Generative Transformers", "architecture"),
    ("iclr", 2023, "Magic3D: High-Resolution Text-to-3D Content Creation", "teaser"),
    ("iclr", 2023, "CogVideo: Large-scale Pretraining for Text-to-Video Generation via Transformers", "architecture"),
    ("iclr", 2023, "ModelScope Text-to-Video Technical Report", "teaser"),
    ("iclr", 2023, "ReAct: Synergizing Reasoning and Acting in Language Models", "conceptual"),
    ("iclr", 2023, "Self-Consistency Improves Chain of Thought Reasoning in Language Models", "conceptual"),
    ("iclr", 2023, "Symbolic Discovery of Optimization Algorithms", "conceptual"),
    ("iclr", 2023, "On the Parameterization and Initialization of Diagonal State Space Models", "architecture"),
    ("iclr", 2023, "DiffDock: Diffusion Steps, Twists, and Turns for Molecular Docking", "teaser"),
    ("iclr", 2023, "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers", "architecture"),
    ("iclr", 2023, "Self-Instruct: Aligning Language Model with Self Generated Instructions", "pipeline"),
    ("iclr", 2023, "Universal Guidance for Diffusion Models", "conceptual"),
    ("iclr", 2023, "Compositional Visual Generation with Composable Diffusion Models", "conceptual"),
    ("iclr", 2023, "DPOK: Reinforcement Learning for Fine-tuning Text-to-Image Diffusion Models", "pipeline"),
    # ---------------- ICLR 2024 ----------------
    ("iclr", 2024, "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?", "pipeline"),
    ("iclr", 2024, "MathVista: Evaluating Mathematical Reasoning of Foundation Models in Visual Contexts", "taxonomy"),
    ("iclr", 2024, "StreamingLLM: Efficient Streaming Language Models with Attention Sinks", "conceptual"),
    ("iclr", 2024, "PixArt-alpha: Fast Training of Diffusion Transformer for Photorealistic Text-to-Image Synthesis", "architecture"),
    ("iclr", 2024, "Flow Straight and Fast: Learning to Generate and Transfer Data with Rectified Flow", "conceptual"),
    ("iclr", 2024, "InstaFlow: One Step is Enough for High-Quality Image Generation", "pipeline"),
    ("iclr", 2024, "LRM: Large Reconstruction Model for Single Image to 3D", "pipeline"),
    ("iclr", 2024, "MetaGPT: Meta Programming for A Multi-Agent Collaborative Framework", "framework"),
    ("iclr", 2024, "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection", "framework"),
    ("iclr", 2024, "RAPTOR: Recursive Abstractive Processing for Tree-Organized Retrieval", "conceptual"),
    ("iclr", 2024, "FreeInit: Bridging Initialization Gap in Video Diffusion Models", "conceptual"),
    ("iclr", 2024, "Video Latent Consistency Model", "pipeline"),
    ("iclr", 2024, "Zero123++: A Single Image to Consistent Multi-view Diffusion Base Model", "pipeline"),
    ("iclr", 2024, "InstantMesh: Efficient 3D Mesh Generation from a Single Image with Sparse-view Large Reconstruction Models", "pipeline"),
    ("iclr", 2024, "Automated Circuit Discovery for Mechanistic Interpretability", "conceptual"),
    ("iclr", 2024, "Representation Engineering: A Top-Down Approach to AI Transparency", "framework"),
    ("iclr", 2024, "AgentBench: Evaluating LLMs as Agents", "taxonomy"),
    ("iclr", 2024, "ToolLLM: Facilitating Large Language Models to Master 16000+ Real-world APIs", "framework"),
    ("iclr", 2024, "LongBench: A Bilingual, Multitask Benchmark for Long Context Understanding", "taxonomy"),
    ("iclr", 2024, "YaRN: Efficient Context Window Extension of Large Language Models", "conceptual"),
    ("iclr", 2024, "AQLM: Extreme Compression of Large Language Models via Additive Quantization", "architecture"),
    ("iclr", 2024, "CRITIC: Large Language Models Can Self-Correct with Tool-Interactive Critiquing", "framework"),
    ("iclr", 2024, "Large Language Models as Tool Makers", "conceptual"),
    ("iclr", 2024, "GAIA: A Benchmark for General AI Assistants", "teaser"),
    ("iclr", 2024, "UniSim: Learning Interactive Real-World Simulators", "teaser"),
    ("iclr", 2024, "IRIS: Learning to Model the World with Language", "framework"),
    ("iclr", 2024, "MAmmoTH: Building Math Generalist Models through Hybrid Instruction Tuning", "pipeline"),
    ("iclr", 2024, "MetaMath: Bootstrap Your Own Mathematical Questions for Large Language Models", "pipeline"),
    ("iclr", 2024, "WizardLM: Empowering Large Language Models to Follow Complex Instructions", "pipeline"),
    ("iclr", 2024, "MLAgentBench: Evaluating Language Models On Machine Learning Experimentation", "framework"),
    ("iclr", 2024, "RoboGen: Towards Unleashing Infinite Data for Automated Robot Skill Learning via Generative Simulation", "pipeline"),
    ("iclr", 2024, "Wuerstchen: Efficient Pretraining of Text-to-Image Models", "architecture"),
    ("iclr", 2024, "Consistency Trajectory Models: Learning Probability Flow ODE Trajectory of Diffusion", "conceptual"),
    ("iclr", 2024, "Habitat 3.0: A Co-Habitat for Humans, Avatars and Robots", "teaser"),
    ("iclr", 2024, "WebArena: A Realistic Web Environment for Building Autonomous Agents", "teaser"),
    ("iclr", 2024, "TD-MPC2: Scalable, Robust World Models for Continuous Control", "architecture"),
    ("iclr", 2024, "Score Entropy Discrete Diffusion", "conceptual"),
    ("iclr", 2024, "OmniQuant: Omnidirectionally Calibrated Quantization for Large Language Models", "architecture"),
    ("iclr", 2024, "TinyLlama: An Open-Source Small Language Model", "pipeline"),
    ("iclr", 2024, "AnimateDiff: Animate Your Personalized Text-to-Image Diffusion Models without Specific Tuning", "pipeline"),
    # ---------------- ICLR 2025 ----------------
    ("iclr", 2025, "TextGrad: Automatic Differentiation via Text", "framework"),
    ("iclr", 2025, "ToolSandbox: A Stateful, Tool-Augmented Environment for Realistic LLM Agent Evaluation", "framework"),
    ("iclr", 2025, "AndroidWorld: A Dynamic Benchmarking Environment for Autonomous Agents", "teaser"),
    ("iclr", 2025, "Agent S: An Open Agentic Framework that Uses Computers Like a Human", "pipeline"),
    ("iclr", 2025, "OmniACT: A Dataset and Benchmark for Enabling Multimodal Generalist Autonomous Computer Agents", "teaser"),
    ("iclr", 2025, "RULER: What's the Real Context Size of Your Long-Context Language Models?", "taxonomy"),
    ("iclr", 2025, "tau-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains", "framework"),
    ("iclr", 2025, "Gated DeltaNet: Gated Delta Networks for Long Context Language Modeling", "architecture"),
    ("iclr", 2025, "Latte: Latent Diffusion Transformer for Video Generation", "architecture"),
    ("iclr", 2025, "GUI Odyssey: A Comprehensive Dataset and Benchmark for Cross-App GUI Navigation on Mobile Devices", "teaser"),
    ("iclr", 2025, "AssistantBench: Can Web Agents Solve Realistic and Time-Consuming Tasks?", "taxonomy"),
    ("iclr", 2025, "Comprehensive RAG Benchmark", "taxonomy"),
    ("iclr", 2025, "SWE-Gym: An Open-Source Platform for Learning How to Reason in Software Engineering", "framework"),
    ("iclr", 2025, "SpinQuant: LLM Quantization with Learnable Rotations", "architecture"),
    ("iclr", 2025, "ToolACE: Winning the Points of LLM Function Calling", "pipeline"),
    ("iclr", 2025, "ProcessBench: Identifying Process Errors in Mathematical Reasoning", "taxonomy"),
    ("iclr", 2025, "Multi-SWE-bench: A Multilingual Benchmark for Issue Resolving", "taxonomy"),
    ("iclr", 2025, "Large Language Diffusion Models", "architecture"),
    ("iclr", 2025, "Discrete Flow Matching", "conceptual"),
]
